### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by Zhaihanlei** [hackerchenzhuo/LaKo#10]
i can not find this file . please help me,thank you 

OSError: Can't load the configuration of '/root/data/LaKo/checkpoint/vqa2.0_large_backbone/checkpoint/best_dev'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/root/data/LaKo/checkpoint/vqa2.0_large_backbone/checkpoint/best_dev' is the correct path to a directory containing a config.json file

**Comment by hackerchenzhuo** [comment]
It seems that you evaluate this model without training and saving it first?

This DIR (```/root/data/LaKo/checkpoint/```) should be the place where the trained model saves.

**Comment by Zhaihanlei** [comment]
But this is the error that pops up when I run this command.  bash run_okvqa_train.sh

**Comment by Zhaihanlei** [comment]
Maybe i need pre-train LaKo (large version) on VQA2.0 ?  How to pre-train LaKo (large version) on VQA2.0?  I need your help thank you

**Comment by hackerchenzhuo** [comment]
> Maybe i need pre-train LaKo (large version) on VQA2.0 ? How to pre-train LaKo (large version) on VQA2.0? I need your help thank you

You can also train LaKo from scratch by setting ```load_path="none";```
<img width="559" alt="image" src="https://user-images.githubusercontent.com/42081540/220037793-32e4531e-0f7c-4040-be56-cbf9aa452bbe.png">

**Comment by hackerchenzhuo** [comment]
All the parameters in ```run_okvqa_train.sh``` are modifiable.

**Comment by Zhaihanlei** [comment]
I got this error when I was training。 could you help me
Training | epoch 1:   0%|                                                                                                                                     | 0/1042 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_reader.py", line 271, in <module>
    train(
  File "train_reader.py", line 67, in train
    train_loss = model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/LaKo-main/src/model.py", line 47, in forward
    return super().forward(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1710, in forward
    encoder_last_hidden_state=encoder_outputs.last_hidden_state,
AttributeError: 'tuple' object has no attribute 'last_hidden_state'

**Comment by hackerchenzhuo** [comment]
Have you installed [Transformers](http://huggingface.co/transformers/) with version 3.0.2?

Try ```pip install Transformers==3.0.2``` ?

@Zhaihanlei

**Comment by Zhaihanlei** [comment]
My version is Transformers==4.22.1

**Comment by hackerchenzhuo** [comment]
Yes, the latest Transformers have some differences from the older version.
You can build a virtual environment for testing.

**Comment by Zhaihanlei** [comment]
t5-large-pytorch_ The model.bin link is too slow to download the model. Which folder should I put it in after I download it locally

**Comment by hackerchenzhuo** [comment]
Maybe this folder? 

```~/.cache/huggingface/transformers/.```

You may be able to download to any path and then let the model read in the corresponding place by specifying the path. You can use Google to search for the specific method since I am a little fuzzy about this part.

**Comment by fjwang3** [comment]
> Have you installed [Transformers](http://huggingface.co/transformers/) with version 3.0.2?
> 
> Try `pip install Transformers==3.0.2` ?
> 
> @Zhaihanlei
I have installed transformers==3.0.2, but the following error always occurs when running the command:bash run_okvqa_train.sh. 
AttributeError: module 'transformers' has no attribute 'TFFiDT5'

**Comment by hackerchenzhuo** [comment]
Please give me the complete error log.

**Comment by fjwang3** [comment]
| |
王凤娟
|
|
***@***.***
|
---- Replied Message ----
| From | Zhuo ***@***.***> |
| Date | 2/23/2023 12:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hackerchenzhuo/LaKo] Model (Issue #10) |

Please give me the complete error log.

**Comment by fjwang3** [comment]
> Please give me the complete error log.
![image](https://user-images.githubusercontent.com/67569951/220900964-8c8b2424-fca4-44df-9e0a-df6d172df0e5.png)

**Comment by hackerchenzhuo** [comment]
> > Maybe i need pre-train LaKo (large version) on VQA2.0 ? How to pre-train LaKo (large version) on VQA2.0? I need your help thank you
> 
> You can also train LaKo from scratch by setting `load_path="none";` <img alt="image" width="559" src="https://user-images.githubusercontent.com/42081540/220037793-32e4531e-0f7c-4040-be56-cbf9aa452bbe.png">

@wangfengjuan Try this.

**Comment by fjwang3** [comment]
> > > Maybe i need pre-train LaKo (large version) on VQA2.0 ? How to pre-train LaKo (large version) on VQA2.0? I need your help thank you
> > 
> > 
> > You can also train LaKo from scratch by setting `load_path="none";` <img alt="image" width="559" src="https://user-images.githubusercontent.com/42081540/220037793-32e4531e-0f7c-4040-be56-cbf9aa452bbe.png">
> 
> @wangfengjuan Try this.
If load_path="none"l, the following error will occur



> > > Maybe i need pre-train LaKo (large version) on VQA2.0 ? How to pre-train LaKo (large version) on VQA2.0? I need your help thank you
> > 
> > 
> > You can also train LaKo from scratch by setting `load_path="none";` <img alt="image" width="559" src="https://user-images.githubusercontent.com/42081540/220037793-32e4531e-0f7c-4040-be56-cbf9aa452bbe.png">
> 
> @wangfengjuan Try this.
if load_path="none"，The following problems will occur again
![image](https://user-images.githubusercontent.com/67569951/220920802-62b2a9f1-7254-47a3-bc55-08ae595d2a9a.png)

**Comment by hackerchenzhuo** [comment]
I sincerely suggest that maybe you could first understand some of the **key codes** and the **working principles** of this paper, which can help you avoid many potential bugs and problems. For example, the issue that you are raising now can be avoided by ```reducing the amount of n_context/ text_maxlength, reducing the batch size, or switching to the base model```, which are all the default principles of model learning.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/42081540/220927135-c27c27a7-b5d6-4627-975a-b9b1d4f7279b.png">


Moreover, there are also some other people releasing related issues which could be available by searching the keyword in this project.
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/42081540/220928059-cadf5ef4-91ee-4aa8-8b10-a51d70505c60.png">
This can lighten my workload as I am also very busy recently. Thank you for your understanding : )

**Comment by hackerchenzhuo** [comment]
Just mortifying the corresponding parameters in the bash file is enough to train VQA2.0  from scratch,  but in fact, you do not have to train VQA2.0. Only training on OKVQA is also acceptable and makes sense.
