### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Zhaihanlei** [hackerchenzhuo/LaKo#11]
Whether the project only needs to train the reader。
Whether the file retriever.py needs training
What is the relationship between retriever and reader during training？
I found some information, but I didn't understand？
Thank you very much for your reply！

**Comment by hackerchenzhuo** [comment]
```Whether the project only needs to train the reader```**[Yes]**
```Whether the file retriever.py needs training``` **[You can try it. It should support the training but the retrieve performance is not as good as I expected so I only discuss it in my paper. Maybe you can improve this part with a better backbone e.g., using pre-trained sentence-bert]**
```What is the relationship between the retriever and the reader during training？```[Please refer to my paper. The following figure could help you understand it better. That is an iterative process where the attention score play the role of a weak supervision signal. You can also refer to the following two paper]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/42081540/221851213-0f9c4255-efd2-4030-8647-ef038a9403d3.png">
Distilling Knowledge from Reader to Retriever:https://arxiv.org/abs/2012.04584.
[Github link to FiD](https://github.com/facebookresearch/FiD)

**Comment by Zhaihanlei** [comment]
Do you have the FIDT5 model structure diagram？For example, VGG or transform shows the diagram of each layer？Thank you very much for your reply！

**Comment by hackerchenzhuo** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/42081540/221864563-ca2129b8-8974-40ea-a1cd-f102ba49108f.png">
Please refer to this paper：https://arxiv.org/abs/2007.01282

**Comment by Zhaihanlei** [comment]
![image](https://user-images.githubusercontent.com/102461299/221867385-878a36d7-bd42-47b8-83c7-b835915f4ac2.png)
I found this. Is this his model?

>

**Comment by hackerchenzhuo** [comment]
Maybe not

**Comment by Zhaihanlei** [comment]
When I run vqa2_deal.py to generate okvqa_train_t5_v5_frequent_bm25, where should I change？
there ![image](https://user-images.githubusercontent.com/102461299/221883997-e7304fc3-72ee-4478-80ea-f67dc3558c19.png)
and there ？
![image](https://user-images.githubusercontent.com/102461299/221884151-94b0dca5-a937-4ec9-8461-f1bb912faae9.png)

**Comment by Zhaihanlei** [comment]
how to change

**Comment by hackerchenzhuo** [comment]
Just provide those related content and run the script. Then you will get the standard input for LaKo.

 p.s. In fact, you can browse the code content, which can help you better understand our purpose and motivation.
