### ISSUE TITLE
It's a  great work! Could you tell me which pertrain model did you use in caption Generation?

### ISSUE THREAD

**Issue by GeoJX** [hackerchenzhuo/LaKo#2]

**Comment by hackerchenzhuo** [comment]
Thanks for your interest in our work!
The pertrained caption model we used is standard Vinvl (-large) here.

**Comment by GeoJX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GeoJX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
