### ISSUE TITLE
Computing power requirements

### ISSUE THREAD

**Issue by fjwang3** [hackerchenzhuo/LaKo#4]
Hello, how much computing power do you use for this work, I don't see it mentioned in the article，Thankyou！

**Comment by hackerchenzhuo** [comment]
Our training environment is 24G NVIDIA RTX 3090 × 7 (We did not use multiple GPU in parallel)

**Comment by fjwang3** [comment]
Thank you and How long did it take to run with 24G NVIDIA RTX 3090 × 7  to get the experimental results?

**Comment by hackerchenzhuo** [comment]
Since the log files were cleaned up before, I forgot the specific time.
Nevertheless, in my impression VQA2.0 spends more than 16h and OKVQA about 2~3h (in a single GPU)?

Different dataset has different required epochs.

**Comment by fjwang3** [comment]
> Since the log files were cleaned up before, I forgot the specific time. Nevertheless, in my impression VQA2.0 spends more than 16h and OKVQA about 2~3h (in a single GPU)?
> 
> Different dataset has different required epochs.
I have been debugging for a long time now, and the following problems always occur. Can you help me? I use single card 3090, 24g memory. We look forward to your reply. thank you
![image](https://user-images.githubusercontent.com/67569951/218905780-20b2754b-d94a-45f1-b83c-b3685bbef9dc.png)

**Comment by hackerchenzhuo** [comment]
Maybe you could try smaller batch sizes for a complete running attempt? @wangfengjuan

**Comment by fjwang3** [comment]
> Maybe you could try smaller batch sizes for a complete running attempt? @wangfengjuan

Yes, I turned down the batch_ Size, we also tried other methods to solve omm, but they didn't work. I don't know where the problem is?

**Comment by hackerchenzhuo** [comment]
Or turned down the number of retrieval facts (n_context) and set the model_size to base？ @wangfengjuan

**Comment by fjwang3** [comment]
> Or turned down the number of retrieval facts (n_context) and set the model_size to base？ @wangfengjuan

Sorry, I set the model_size to base, and n_ Context=2, still can't solve the problem, or the display memory is insufficient.

**Comment by hackerchenzhuo** [comment]
smaller text_maxlength? You should delete the following shell code:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/42081540/219028121-558b3981-7157-46ab-a71c-e71f9d3637ec.png">
@wangfengjuan

**Comment by fjwang3** [comment]
> smaller text_maxlength? You should delete the following shell code: <img alt="image" width="298" src="https://user-images.githubusercontent.com/42081540/219028121-558b3981-7157-46ab-a71c-e71f9d3637ec.png"> @wangfengjuan

and Setting text_maxlength=2 and deleting those codes. The same problem will still occur, as follows
![image](https://user-images.githubusercontent.com/67569951/219032962-d42187ce-95d4-4da8-b41c-99bc6a659335.png)

**Comment by hackerchenzhuo** [comment]
Can you debug the entire code with PDB to find the place where the GPU memory usage suddenly increases? It was no problem for me to run before. In theory, it is impossible for the **base model** to exceed the GPU memory. @wangfengjuan 

RTX 3090 24g memory should be enough.

**Comment by wangfengjuan** [comment]
> 

Let me try. I feel that this is not a problem of parameter setting, but a problem of other settings. however, I haven't found the key to the problem

**Comment by fjwang3** [comment]
> Let me try. I feel that this is not a problem of parameter setting, but a problem of other settings. however, I haven't found the key to the problem



> Can you debug the entire code with PDB to find the place where the GPU memory usage suddenly increases? It was no problem for me to run before. In theory, it is impossible for the **base model** to exceed the GPU memory. @wangfengjuan
> 
> RTX 3090 24g memory should be enough.

Let me try. I feel that this is not a problem of parameter setting, but a problem of other settings. however, I haven't found the key to the problem

**Comment by fjwang3** [comment]
> Can you debug the entire code with PDB to find the place where the GPU memory usage suddenly increases? It was no problem for me to run before. In theory, it is impossible for the **base model** to exceed the GPU memory. @wangfengjuan
> 
> RTX 3090 24g memory should be enough.
Thank you. I have solved this problem. I am running the command: bash run_ okvqa_ At train.sh, I encountered another problem. I also tried many online methods, but still did not solve it
![image](https://user-images.githubusercontent.com/67569951/219992345-7700e949-f8c0-4515-a08a-77db783a8031.png)

**Comment by hackerchenzhuo** [comment]
This problem is strange since there is not any TensorFlow content in my code.
I suggest that when the model fails, you can provide the corresponding location for error line.
