### ISSUE TITLE
about the data and model link

### ISSUE THREAD

**Issue by blldd** [hackerchenzhuo/LaKo#6]
Thank you for your wonderful work, and I am working on reproducing, and could you please share the data and model link? Thanks a lot.

**Comment by hackerchenzhuo** [comment]
Thanks for your comments. 
Nevertheless, what is the  the data and model **link** you refer to?

We have offered all the data/code for LaKo in this project, maybe you could refer to other [closed issues](https://github.com/hackerchenzhuo/LaKo/issues?q=is%3Aissue+is%3Aclosed) for help?
<img width="773" alt="image" src="https://user-images.githubusercontent.com/42081540/210525430-59ae6c12-0a56-4c51-ab22-4f8a3fee250b.png">

**Comment by blldd** [comment]
I am not sure how to generate the train_data='okvqa_train_t5_v5_frequent_bm25.json' in .sh file, maybe the output file 'vqa2_train_t5_3_v5_frequent_bm25' of vqa2_deal.py?

**Comment by blldd** [comment]
could you please give me a requirements.txt file, thanks a lot.

when i run bash run_okvqa_train.sh, found this error:

transformers==3.0.2

Traceback (most recent call last):
  File "train_reader.py", line 231, in <module>
    tokenizer = transformers.T5Tokenizer.from_pretrained(model_name, cache_dir=cache_dir)
  File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1140, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1246, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 't5-base' was not found in tokenizers model name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). We assumed 't5-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.

transformers==4.10.0

Traceback (most recent call last):
  File "train_reader.py", line 281, in <module>
    tokenizer
  File "train_reader.py", line 87, in train
    dev_em = evaluate(model, eval_dataset, tokenizer, collator, opt, tk_tokenizer, pt_stemmer)
  File "train_reader.py", line 145, in evaluate
    max_length=50
  File "/mnt/lustressd/lidedong1/workspace/MLP/projects/LaKo/src/model.py", line 60, in generate
    max_length=max_length
  File "/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/lustre/lidedong1/.local/lib/python3.6/site-packages/transformers/generation_utils.py", line 933, in generate
    raise ValueError("Make sure that `model_kwargs` include `encoder_outputs` of type `ModelOutput`.")
ValueError: Make sure that `model_kwargs` include `encoder_outputs` of type `ModelOutput`.

Can you figure out why?

**Comment by blldd** [comment]
If I want to test a new image with the well-trained model, how should I do it? Could you please provide this part of the script? Thanks!

**Comment by BigHyf** [comment]
> 

You can understand that okvqa and vqa2.0 have the same data processing

**Comment by blldd** [comment]
> > 
> 
> You can understand that okvqa and vqa2.0 have the same data processing

Is there any parameters change in function load_init() for okvqa/vqa2.0?

**Comment by BigHyf** [comment]
> load_init()

I'm under the impression it's pretty much the same, you can look at the file directory of the data.

**Comment by blldd** [comment]
> > load_init()
> 
> I'm under the impression it's pretty much the same, you can look at the file directory of the data.

data_process/data/okvqa have 3/train.json and 1/valid.json, however data_process/data/vqa2.0 donnot have the train/valid file.

**Comment by hackerchenzhuo** [comment]
Well, in fact some data is generated by our scripts. You could firstly look through the original OKVQA/VQA2.0 resource and find their distinction compared with our data source.

This could really help you understand our motivation and data processing process.

**Comment by blldd** [comment]
> Well, in fact some data is generated by our scripts. You could firstly look through the original OKVQA/VQA2.0 resource and find their distinction compared with our data source.
> 
> This could really help you understand our motivation and data processing process.

OK, Thanks for your reply.

**Comment by blldd** [comment]
I am not sure how to generate retriever_train_data="okvqa_train_t5_v5_frequent_bm25_${attention_part}_${model_size}_with_${attention_score_style}_${version}.json";
 and retriever_eval_data, could you please interpret how to generate them? Thanks a lot :)

**Comment by hackerchenzhuo** [comment]
- This is the **attention score style**(max/mean) and **attention_part**(half/full):

<img width="449" alt="image" src="https://user-images.githubusercontent.com/42081540/210728696-dcc8afd1-e2b5-4fb7-b608-e3a4195a780c.png">

- **Model_size** could be large/base
- I suggest you to understand the principle of [FiD and DPR](https://github.com/facebookresearch/FiD) 

The following three papers may be helpful for reference:
- [Leveraging passage retrieval with generative models for open domain question answering](https://arxiv.org/abs/2007.01282)
- [Dense Passage Retrieval for Open-Domain Question Answering](https://arxiv.org/abs/2004.04906)
- [Distilling knowledge from reader to retriever for question answering](https://arxiv.org/abs/2012.04584)

**Comment by blldd** [comment]
Thank you for your help and patience, it helps me a lot.
