### ISSUE TITLE
How to process new images with a trained model

### ISSUE THREAD

**Issue by blldd** [hackerchenzhuo/LaKo#8]
What should I do if I want to test a new image with the trained model?  Could you please provide this part of the script? Thanks!

**Comment by hackerchenzhuo** [comment]
You should firstly generate the image caption.

**Comment by BigHyf** [comment]
https://github.com/microsoft/Oscar/blob/master/VinVL_MODEL_ZOO.md, you can follow this to generate the image caption. If you have any questions, you can look at the relevant issues.

**Comment by blldd** [comment]
Thanks for your reply! 
Due to the environment/data problems in the reproduction, it is difficult to train the model in a short time, so I was wondering that can you upload the well-trained model for us to quickly test and learn?

**Comment by hackerchenzhuo** [comment]
> Thanks for your reply! Due to the environment/data problems in the reproduction, it is difficult to train the model in a short time, so I was wondering that can you upload the well-trained model for us to quickly test and learn?

We are sorry that our Linux server has been reinstall several monthes ago while this work has been finished for more than 8 monthes. All the available cache files that you need should have been uploaded by us.

Maybe you could simply train a LaKo-base in seperated tiny data for evaluation.
